# Importing Libraries

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

# Importing Data

In [2]:
# Creating Path
path = r'C:\Users\jenni\OneDrive\Documenten\Data Analyst Program\Data Analytics Immersion\Achievement 6\Gun violence data\02 Data'

In [16]:
#Importing Dataset
df_gun = pd.read_csv(os.path.join(path, 'Raw Data', 'gun-violence-data_01-2013_03-2018.csv'))

# Consistency Checks

In [5]:
df_gun.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [9]:
df_gun.tail()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url_fields_missing,congressional_district,gun_stolen,...,n_guns_involved,notes,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,state_house_district,state_senate_district
239672,1083142,2018-03-31,Louisiana,Rayne,North Riceland Road and Highway 90,0,0,False,NaN,0::Unknown,...,1.0,NaN,0::25,0::Adult 18+,0::Female,NaN,"0::Unharmed, Arrested",0::Subject-Suspect,NaN,NaN
239673,1083139,2018-03-31,Louisiana,Natchitoches,247 Keyser Ave,1,0,False,4.0,0::Unknown,...,1.0,NaN,1::21,0::Adult 18+||1::Adult 18+,0::Male||1::Male,NaN,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect,23.0,31.0
239674,1083151,2018-03-31,Louisiana,Gretna,1300 block of Cook Street,0,1,False,2.0,0::Unknown,...,1.0,NaN,0::21,0::Adult 18+,0::Male,NaN,0::Injured,0::Victim,85.0,7.0
239675,1082514,2018-03-31,Texas,Houston,12630 Ashford Point Dr,1,0,False,9.0,0::Unknown,...,1.0,"Vic was found shot to death in car on 4/1/18, ...",0::42,0::Adult 18+,0::Male,NaN,0::Killed,0::Victim,149.0,17.0
239676,1081940,2018-03-31,Maine,Norridgewock,434 Skowhegan Rd,2,0,False,2.0,0::Unknown||1::Unknown,...,2.0,"ALT: US 2, shot wife then self, handgun, shotg...",0::58||1::62,0::Adult 18+||1::Adult 18+,0::Female||1::Male,1::Significant others - current or former,0::Killed||1::Killed,0::Victim||1::Subject-Suspect,111.0,3.0

In [13]:
df_gun.describe().round(0)

,incident_id,n_killed,n_injured,congressional_district,latitude,longitude,n_guns_involved,state_house_district,state_senate_district
count,239677.0,239677.0,239677.0,227733.0,231754.0,231754.0,140226.0,200905.0,207342.0
mean,559334.0,0.0,0.0,8.0,38.0,-89.0,1.0,55.0,20.0
std,293129.0,1.0,1.0,8.0,5.0,14.0,5.0,42.0,14.0
min,92114.0,0.0,0.0,0.0,19.0,-171.0,1.0,1.0,1.0
25%,308545.0,0.0,0.0,2.0,34.0,-94.0,1.0,21.0,9.0
50%,543587.0,0.0,0.0,5.0,39.0,-86.0,1.0,47.0,19.0
75%,817228.0,0.0,1.0,10.0,41.0,-80.0,1.0,84.0,30.0
max,1083472.0,50.0,53.0,53.0,71.0,97.0,400.0,901.0,94.0

In [14]:
df_gun.shape

(239677, 25)

In [17]:
# Dropping unnecessary Columns
df_gun.drop(columns = {'incident_url', 'source_url', 'participant_name', 'sources', 'notes', 'incident_url_fields_missing', 'location_description'}, inplace = True)

In [18]:
# Finding Missing values
df_gun.isnull().sum()

incident_id                      0
date                             0
state                            0
city_or_county                   0
address                      16497
n_killed                         0
n_injured                        0
congressional_district       11944
gun_stolen                   99498
gun_type                     99451
incident_characteristics       326
latitude                      7923
longitude                     7923
n_guns_involved              99451
participant_age              92298
participant_age_group        42119
participant_gender           36362
participant_relationship    223903
participant_status           27626
participant_type             24863
state_house_district         38772
state_senate_district        32335
dtype: int64

In [20]:
# Dropping columns with too many missing values
df_gun.drop(columns = {'gun_stolen', 'gun_type', 'n_guns_involved', 'participant_age', 'participant_relationship'}, inplace = True)

In [22]:
#Check for Mixed Types
for col in df_gun.columns.tolist():
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_gun[weird]) > 0:
    print (col)

C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)

address

C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)

incident_characteristics

C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)

participant_age_group
participant_gender
participant_status

C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)
C:\Users\jenni\AppData\Local\Temp\ipykernel_12548\3446827747.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  weird = (df_gun[[col]].applymap(type) != df_gun[[col]].iloc[0].apply(type)).any(axis = 1)

participant_type

In [23]:
# Changing Data Type of mixed columns
df_gun[['address', 'incident_characteristics', 'participant_age_group', 'participant_gender', 'participant_status', 'participant_type']] = df_gun[['address', 'incident_characteristics', 'participant_age_group', 'participant_gender', 'participant_status', 'participant_type']].astype('str')

In [24]:
df_gun.dtypes

incident_id                   int64
date                         object
state                        object
city_or_county               object
address                      object
n_killed                      int64
n_injured                     int64
congressional_district      float64
incident_characteristics     object
latitude                    float64
longitude                   float64
participant_age_group        object
participant_gender           object
participant_status           object
participant_type             object
state_house_district        float64
state_senate_district       float64
dtype: object

In [25]:
# Looking for duplicates
df_dups = df_gun[df_gun.duplicated()]

In [26]:
df_dups

Empty DataFrame
Columns: [incident_id, date, state, city_or_county, address, n_killed, n_injured, congressional_district, incident_characteristics, latitude, longitude, participant_age_group, participant_gender, participant_status, participant_type, state_house_district, state_senate_district]
Index: []

In [28]:
# Export products Dataframe
df_gun.to_csv(os.path.join(path, 'Prepared Data', 'gun_violence_clean.csv'))